// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1P_Kc4NAW6nxhac1cGmqzmpLz6AMTitk',
    appId: '1:649218599394:web:e4200434a9b91911aab1bb',
    messagingSenderId: '649218599394',
    projectId: 'messagingflashchat',
    authDomain: 'messagingflashchat.firebaseapp.com',
    storageBucket: 'messagingflashchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7nDrzyf5nQcGC2HGr2jbUvA8-m-3Rco',
    appId: '1:649218599394:android:57ff76a889abb25caab1bb',
    messagingSenderId: '649218599394',
    projectId: 'messagingflashchat',
    storageBucket: 'messagingflashchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvuqTNLlXKfy2IGdr7DN1vGzbFdDrlw9w',
    appId: '1:649218599394:ios:8458f50ef0146972aab1bb',
    messagingSenderId: '649218599394',
    projectId: 'messagingflashchat',
    storageBucket: 'messagingflashchat.appspot.com',
    iosBundleId: 'com.example.chatMessagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvuqTNLlXKfy2IGdr7DN1vGzbFdDrlw9w',
    appId: '1:649218599394:ios:8458f50ef0146972aab1bb',
    messagingSenderId: '649218599394',
    projectId: 'messagingflashchat',
    storageBucket: 'messagingflashchat.appspot.com',
    iosBundleId: 'com.example.chatMessagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1P_Kc4NAW6nxhac1cGmqzmpLz6AMTitk',
    appId: '1:649218599394:web:1fa15917b25d599faab1bb',
    messagingSenderId: '649218599394',
    projectId: 'messagingflashchat',
    authDomain: 'messagingflashchat.firebaseapp.com',
    storageBucket: 'messagingflashchat.appspot.com',
  );

}